---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sevtify.
--- DateTime: 2026-04-01 05:35
---
local jwt    = require "resty.jwt"
local SECRET = os.getenv("STREAM_JWT_SECRET")  -- partagé avec FastAPI

local function reject(code, msg)
    ngx.status = code
    ngx.say(msg)
    ngx.exit(code)
end

-- 1. Récupération du token depuis le query param ou le header Authorization
local token = ngx.var.arg_token
if not token then
    local auth = ngx.req.get_headers()["Authorization"]
    if auth then
        token = auth:match("Bearer%s+(.+)")
    end
end

if not token then
    return reject(401, "Token manquant")
end

-- 2. Vérification de la signature et de l'expiration (resty.jwt fait tout)
local verified = jwt:verify(SECRET, token)
if not verified.verified then
    return reject(403, "Token invalide : " .. (verified.reason or "inconnu"))
end

local payload = verified.payload

-- 3. Vérification de l'expiration
if payload.exp and payload.exp < ngx.time() then
    return reject(401, "Token expiré")
end

-- 4. Vérification que le media_id du token correspond à l'URL demandée
--    URI attendue : /hls/{media_id}/...
local uri_media_id = ngx.var.uri:match("^/hls/([^/]+)/")
if not uri_media_id then
    return reject(400, "URL invalide")
end

if payload.media_id ~= uri_media_id then
    return reject(403, "Token non valide pour ce média")
end

-- 5. Tout est bon — on expose le media_id pour Nginx si besoin
ngx.var.upstream_media_id = payload.media_id