services:
  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: journal_IAI_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
    ports:
      - "${BD_OUTPUT_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: ${START_PERIOD:-5}s

  # Cache/Broker Redis
  redis:
      image: redis:7-alpine
      container_name: journal_IAI_redis
      ports:
        - "${REDIS_CACHE_PORT}:6379"
      command: redis-server --appendonly yes # Active la persistance sur disque
      volumes:
        - redis_data:/data # Persistance réelle des données Redis
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 20s
        timeout: 10s
        retries: 10
        start_period: ${START_PERIOD:-5}s
      restart: unless-stopped

  # Stockage d'objets MinIO
  minio:
      image: minio/minio:latest
      container_name: journal_IAI_minio
      environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
        MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      ports:
        - "${MINIO_API_PORT}:9000"
        - "${MINIO_CONSOLE_PORT}:9001"
      command: server /data --console-address ":9001"
      volumes:
        - minio_data:/data
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
        interval: 20s
        timeout: 10s
        retries: 10
        start_period: 60s
      restart: unless-stopped
  minio-init:
    build: .
    container_name: journal_IAI_minio_init
    volumes:
      - .:/app
    command: python -m app.storage.minio_config
    depends_on:
      minio:
        condition: service_healthy
    restart: "no"
  # Backend FastAPI
  api:
    build: .
    container_name: journal_IAI_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "${API_PORT:-8000}:8000"      # Expose le port 8000 de l'API sur le port défini dans .env ou 8000 par défaut
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: ${START_PERIOD:-5}s
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully

  # Reverse Proxy Nginx
  nginx:
    image: nginx:alpine
    container_name: journal_IAI_nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
      - "8181:8181"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/cache:/var/cache/nginx # Le dossier de cache persistant
    healthcheck:
      test: [ "CMD-SHELL",
    "wget -qO- --header='Host: api.iai-journal.test' http://nginx/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s
    depends_on:
      api:
        condition: service_healthy
      minio:
        condition: service_healthy

  # Worker Celery (Traitement images/vidéos, tâches de fond)
  worker:
    build: .
    container_name: journal_IAI_worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  # Flower (DashBoard de Monitoring pour Celery)
  flower:
    image: mher/flower:latest
    container_name: journal_IAI_flower
    ports:
      - "${FLOWER_PORT}:5555"
    command: celery --broker=redis://redis:6379/0 flower
    depends_on:
      redis:
        condition: service_healthy

volumes:
  db_data:
  minio_data:
  redis_data:


