"""Ajout de champs par défaut et changements de certains string en Enum

Revision ID: 02a065f93b39
Revises: 89799dbf9a87
Create Date: 2026-02-12 09:50:15.352424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02a065f93b39'
down_revision: Union[str, Sequence[str], None] = '89799dbf9a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    typeactions_enum = sa.Enum(
        'CREATION',
        'ACCESSION',
        'MODIFICATION',
        'SUPPRESSION',
        name='typeactions'
    )

    moderationtargettype_enum = sa.Enum(
        'POST',
        'COMMENT',
        'USER',
        name='moderationtargettype'
    )

    # Create enums
    typeactions_enum.create(op.get_bind(), checkfirst=True)
    moderationtargettype_enum.create(op.get_bind(), checkfirst=True)

    # Alter audit_logs.action
    op.alter_column(
        'audit_logs',
        'action',
        existing_type=sa.VARCHAR(length=100),
        type_=typeactions_enum,
        existing_nullable=False,
        postgresql_using="action::typeactions"
    )

    # Drop unused columns
    op.drop_column('audit_logs', 'new_values')
    op.drop_column('audit_logs', 'old_values')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')

    # Alter moderation_logs.target_type
    op.alter_column(
        'moderation_logs',
        'target_type',
        existing_type=sa.VARCHAR(length=50),
        type_=moderationtargettype_enum,
        existing_nullable=False,
        postgresql_using="target_type::moderationtargettype"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'moderation_logs',
        'target_type',
        existing_type=sa.Enum('POST', 'COMMENT', 'USER', name='moderationtargettype'),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        postgresql_using="target_type::text"
    )

    op.add_column('audit_logs', sa.Column('ip_address', postgresql.INET(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.TEXT(), nullable=True))
    op.add_column('audit_logs', sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    op.alter_column(
        'audit_logs',
        'action',
        existing_type=sa.Enum('CREATION', 'ACCESSION', 'MODIFICATION', 'SUPPRESSION', name='typeactions'),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
        postgresql_using="action::text"
    )

    sa.Enum('POST', 'COMMENT', 'USER', name='moderationtargettype').drop(op.get_bind(), checkfirst=True)
    sa.Enum('CREATION', 'ACCESSION', 'MODIFICATION', 'SUPPRESSION', name='typeactions').drop(op.get_bind(),
                                                                                             checkfirst=True)

# ### end Alembic commands ###
