"""Modification des noms des attributs pour rendre plus clairs et modification de la colonne destination_entity_id en non nullable

Revision ID: 08395946c10d
Revises: 784791b2a7f4
Create Date: 2026-02-19 23:20:07.532803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08395946c10d'
down_revision: Union[str, Sequence[str], None] = '784791b2a7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('destination_entity_type', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('destination_entity_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('idx_audit_logs_entity'), table_name='audit_logs')
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['destination_entity_type', 'destination_entity_id', 'created_at'], unique=False)
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.drop_column('audit_logs', 'destination_entity_id')
    op.drop_column('audit_logs', 'destination_entity_type')
    # ### end Alembic commands ###
