"""Modifiaction majeure de la bd, ajout du support des classes, annees academic, story et vues des stories et Post

Revision ID: 097b0856e30f
Revises: 7ef5c8c64122
Create Date: 2026-03-02 07:54:48.097728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '097b0856e30f'
down_revision: Union[str, Sequence[str], None] = '7ef5c8c64122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('F', 'M', name='sexetype').create(op.get_bind())
    op.create_table('academic_year',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('libelle', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date > start_date', name='chk_academic_year_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_index('idx_academic_year_active_id', 'academic_year', ['active', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_academic_year_active', 'academic_year', ['active'], unique=True, postgresql_where=sa.text('active = true AND deleted_at IS NULL'))
    op.create_table('classe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classe_prefix', postgresql.ENUM('TC1', 'TC2', 'GLSI_3', 'ASR_3', 'MTWI_3', name='classetype', create_type=False), nullable=False),
    sa.Column('classe_suffix', sa.String(length=1), nullable=True),
    sa.Column('effectif', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False, comment="Référence de l'année académique à laquelle cette classe appartient"),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('effectif >= 0', name='chk_effectif_valid'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_classe_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_classe_created_at_id', 'classe', ['created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_prefix_suffix_academic_year', 'classe', ['classe_prefix', 'classe_suffix', 'academic_year_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('stories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=True),
    sa.Column('target_classe_id', sa.Uuid(), nullable=True, comment='Si la story est ciblée vers une classe spécifique (ex: annonce pour la promo 2023), sinon NULL pour une story générale.'),
    sa.Column('media_url', sa.String(length=500), nullable=False, comment='URL MinIO du média associé à la story (image, vidéo, etc.)'),
    sa.Column('media_type', postgresql.ENUM('IMAGE', 'VIDEO', name='mediatype', create_type=False), nullable=False, comment='Type du média (image, vidéo, etc.) - utilisé pour le rendu côté client'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='URL MinIO de la miniature du média (pour les vidéos ou les images très lourdes) - peut être NULL pour les images légères'),
    sa.Column('legend', sa.String(length=200), nullable=True, comment='Légende optionnelle pour la story, affichée sous le média'),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_expired', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment="Date et heure d'expiration de la story (généralement 24h après la création)"),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_stories_author', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='fk_stories_club', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_classe_id'], ['classe.id'], name='fk_stories_classe', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stories_by_author', 'stories', ['author_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('is_expired = false'))
    op.create_index('idx_stories_by_club', 'stories', ['club_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('is_expired = false AND club_id IS NOT NULL'))
    op.create_index('idx_stories_feed_pagination', 'stories', ['created_at', 'id'], unique=False, postgresql_where=sa.text('is_expired = false'))
    op.create_table('post_views',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_viewed_post_posts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_viewed_post_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id', name='pk_post_views')
    )
    op.create_index('viewed_at_index', 'post_views', ['viewed_at'], unique=False)
    op.create_table('story_views',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name='fk_viewed_story_story', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_viewed_story_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'user_id', name='pk_story_views')
    )
    op.create_index('viewed_at_story_index', 'story_views', ['viewed_at'], unique=False)
    op.add_column('posts', sa.Column('academic_year_id', sa.Uuid(), nullable=True, comment='Année académique à laquelle ce post est associé. Permet de filtrer les posts par année scolaire, même pour les posts généraux qui ne sont pas liés à un club ou un événement spécifique.'))
    op.add_column('posts', sa.Column('target_classe_id', sa.Uuid(), nullable=True, comment='Si le post est ciblé vers une classe spécifique (ex: annonce pour la promo 2023), sinon NULL pour un post général.'))
    op.create_foreign_key(None, 'posts', 'classe', ['target_classe_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'posts', 'academic_year', ['academic_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('registration_jeton', sa.Column('sexe', postgresql.ENUM('F', 'M', name='sexetype', create_type=False), nullable=False))
    op.add_column('registration_jeton', sa.Column('classe_id', sa.Uuid(), nullable=True, comment="Référence à la classe de l'utilisateur (peut être NULL pour les membres du bureau ou les anciens élèves qui ne sont plus rattachés à une classe active)"))
    op.drop_index(op.f('idx_registration_jeton_classe'), table_name='registration_jeton')
    op.create_index('idx_registration_jeton_classe', 'registration_jeton', ['classe_id', 'added_at'], unique=False)
    op.create_foreign_key('fk_registration_jeton_classe', 'registration_jeton', 'classe', ['classe_id'], ['id'], ondelete='SET NULL')
    op.drop_column('registration_jeton', 'classe')
    op.add_column('users', sa.Column('sexe', postgresql.ENUM('F', 'M', name='sexetype', create_type=False), nullable=False))
    op.add_column('users', sa.Column('classe_id', sa.Uuid(), nullable=True, comment="Référence à la classe de l'utilisateur (peut être NULL pour les membres du bureau ou les anciens élèves qui ne sont plus rattachés à une classe active)"))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_users_classe'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_users_classe', 'users', ['classe_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_foreign_key('fk_users_classe', 'users', 'classe', ['classe_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'classe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('classe', postgresql.ENUM('TC1', 'TC2', 'GLSI_3', 'ASR_3', 'MTWI_3', name='classetype', create_type=False), autoincrement=False, nullable=False))
    op.drop_constraint('fk_users_classe', 'users', type_='foreignkey')
    op.drop_index('idx_users_classe', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_users_classe'), 'users', ['classe'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('users', 'classe_id')
    op.drop_column('users', 'sexe')
    op.add_column('registration_jeton', sa.Column('classe', postgresql.ENUM('TC1', 'TC2', 'GLSI_3', 'ASR_3', 'MTWI_3', name='classetype', create_type=False), autoincrement=False, nullable=False))
    op.drop_constraint('fk_registration_jeton_classe', 'registration_jeton', type_='foreignkey')
    op.drop_index('idx_registration_jeton_classe', table_name='registration_jeton')
    op.create_index(op.f('idx_registration_jeton_classe'), 'registration_jeton', ['classe', 'added_at'], unique=False)
    op.drop_column('registration_jeton', 'classe_id')
    op.drop_column('registration_jeton', 'sexe')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'target_classe_id')
    op.drop_column('posts', 'academic_year_id')
    op.drop_index('viewed_at_story_index', table_name='story_views')
    op.drop_table('story_views')
    op.drop_index('viewed_at_index', table_name='post_views')
    op.drop_table('post_views')
    op.drop_index('idx_stories_feed_pagination', table_name='stories', postgresql_where=sa.text('is_expired = false'))
    op.drop_index('idx_stories_by_club', table_name='stories', postgresql_where=sa.text('is_expired = false AND club_id IS NOT NULL'))
    op.drop_index('idx_stories_by_author', table_name='stories', postgresql_where=sa.text('is_expired = false'))
    op.drop_table('stories')
    op.drop_index('uq_prefix_suffix_academic_year', table_name='classe', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_classe_created_at_id', table_name='classe', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('classe')
    op.drop_index('uq_academic_year_active', table_name='academic_year', postgresql_where=sa.text('active = true AND deleted_at IS NULL'))
    op.drop_index('idx_academic_year_active_id', table_name='academic_year', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('academic_year')
    sa.Enum('F', 'M', name='sexetype').drop(op.get_bind())
    # ### end Alembic commands ###
