"""Modification de la structure de story groups

Revision ID: 1afa64907ee9
Revises: e6be234bf22a
Create Date: 2026-04-09 09:44:42.647425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1afa64907ee9'
down_revision: Union[str, Sequence[str], None] = 'e6be234bf22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CLASSE_GROUP', 'CLUB_GROUP', 'USER_GROUP', name='storygroupstype').create(op.get_bind())
    op.drop_index(op.f('idx_stories_by_club'), table_name='stories', postgresql_where='((is_expired = false) AND (club_id IS NOT NULL))')
    op.drop_constraint(op.f('fk_stories_classe'), 'stories', type_='foreignkey')
    op.drop_constraint(op.f('fk_stories_club'), 'stories', type_='foreignkey')
    op.drop_column('stories', 'target_classe_id')
    op.drop_column('stories', 'club_id')
    op.add_column('story_groups', sa.Column('group_type', postgresql.ENUM('CLASSE_GROUP', 'CLUB_GROUP', 'USER_GROUP', name='storygroupstype', create_type=False), nullable=False))
    op.add_column('story_groups', sa.Column('club_id', sa.Uuid(), nullable=True))
    op.add_column('story_groups', sa.Column('target_classe_id', sa.Uuid(), nullable=True))
    op.add_column('story_groups', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('story_groups', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('uq_clause_active_group', 'story_groups', ['target_classe_id'], unique=True, postgresql_where=sa.text('is_active = true AND target_classe_id IS NOT NULL'))
    op.create_index('uq_club_active_group', 'story_groups', ['club_id'], unique=True, postgresql_where=sa.text('is_active = true AND club_id IS NOT NULL'))
    op.create_foreign_key('fk_stories_club', 'story_groups', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_stories_classe', 'story_groups', 'classe', ['target_classe_id'], ['id'], ondelete='SET NULL')
    op.drop_column('story_groups', 'is_expired')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_groups', sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_stories_classe', 'story_groups', type_='foreignkey')
    op.drop_constraint('fk_stories_club', 'story_groups', type_='foreignkey')
    op.drop_index('uq_club_active_group', table_name='story_groups', postgresql_where=sa.text('is_active = true AND club_id IS NOT NULL'))
    op.drop_index('uq_clause_active_group', table_name='story_groups', postgresql_where=sa.text('is_active = true AND target_classe_id IS NOT NULL'))
    op.alter_column('story_groups', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('story_groups', 'is_active')
    op.drop_column('story_groups', 'target_classe_id')
    op.drop_column('story_groups', 'club_id')
    op.drop_column('story_groups', 'group_type')
    op.add_column('stories', sa.Column('club_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('target_classe_id', sa.UUID(), autoincrement=False, nullable=True, comment='Si la story est ciblée vers une classe spécifique (ex: annonce pour la promo 2023), sinon NULL pour une story générale.'))
    op.create_foreign_key(op.f('fk_stories_club'), 'stories', 'clubs', ['club_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stories_classe'), 'stories', 'classe', ['target_classe_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_stories_by_club'), 'stories', ['club_id', 'created_at', 'id'], unique=False, postgresql_where='((is_expired = false) AND (club_id IS NOT NULL))')
    sa.Enum('CLASSE_GROUP', 'CLUB_GROUP', 'USER_GROUP', name='storygroupstype').drop(op.get_bind())
    # ### end Alembic commands ###
