"""Ajout de nouvelles colonnes sur la table posts

Revision ID: 2834fc41e8b7
Revises: 9db90c0cbe55
Create Date: 2026-03-28 01:56:55.384524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2834fc41e8b7'
down_revision: Union[str, Sequence[str], None] = '9db90c0cbe55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('blur_hash', sa.String(length=255), nullable=True))
    op.add_column('post_media', sa.Column('stored_bucket_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_media', 'stored_bucket_name')
    op.drop_column('post_media', 'blur_hash')
    # ### end Alembic commands ###
