"""Ajout colonne executive_role dans RegistrationJeton

Revision ID: 28820b1323af
Revises: 2834fc41e8b7
Create Date: 2026-04-03 14:43:11.273870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28820b1323af'
down_revision: Union[str, Sequence[str], None] = '2834fc41e8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_jeton', sa.Column('executive_role', postgresql.ENUM('DELEGUE_GENERAL', 'DELEGUE_GENERAL_ADJOINT', 'SECRETAIRE_GENERAL', 'SECRETAIRE_GENERAL_ADJOINT', 'CACA', 'VICE_CACA', 'TRESORIER_GENERAL', 'VICE_TRESORIER_GENERAL', 'CONSEILLER_1', 'CONSEILLER_2', name='executiveroletype', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_jeton', 'executive_role')
    # ### end Alembic commands ###
