"""Schema Initial

Revision ID: 2c00283384af
Revises: 
Create Date: 2026-02-08 17:46:51.147530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c00283384af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('member_count >= 0', name='chk_clubs_member_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_clubs_created_at_id', 'clubs', ['created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_clubs_deleted_at', 'clubs', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_clubs_is_active', 'clubs', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_index('idx_clubs_slug', 'clubs', ['slug'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('registration_jeton',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jeton', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'CLUB_LEADER', 'DELEGATE', 'GENERAL_DELEGATE', 'SECRETAIRE_GENERAL', 'EXECUTIVE_MEMBER', 'MODERATOR', 'ADMIN', 'SPECTATOR', name='userrole'), nullable=False),
    sa.Column('classe', sa.Enum('TC1', 'TC2', 'GLSI_3', 'ASR_3', 'MTWI_3', name='classetype'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jeton')
    )
    op.create_index('idx_registration_jeton_classe', 'registration_jeton', ['classe', 'added_at'], unique=False)
    op.create_index('idx_registration_jeton_jeton', 'registration_jeton', ['jeton'], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_index('idx_registration_jeton_unused', 'registration_jeton', ['used_at'], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_event_id', sa.Uuid(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('organizer_club_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='chk_events_dates'),
    sa.ForeignKeyConstraint(['organizer_club_id'], ['clubs.id'], name='fk_events_organizer_club', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_event_id'], ['events.id'], name='fk_events_parent_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_events_created_at_id', 'events', ['created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_events_deleted_at', 'events', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_events_organizer_club_id', 'events', ['organizer_club_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND organizer_club_id IS NOT NULL'))
    op.create_index('idx_events_slug', 'events', ['slug'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_events_start_date', 'events', ['start_date'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_events_status', 'events', ['status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('classe', sa.Enum('TC1', 'TC2', 'GLSI_3', 'ASR_3', 'MTWI_3', name='classetype'), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'CLUB_LEADER', 'DELEGATE', 'GENERAL_DELEGATE', 'SECRETAIRE_GENERAL', 'EXECUTIVE_MEMBER', 'MODERATOR', 'ADMIN', 'SPECTATOR', name='userrole'), nullable=False),
    sa.Column('can_post', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('access_jeton', sa.Uuid(), nullable=True, comment="Référence au jeton d'inscription utilisé"),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('bio IS NULL OR LENGTH(bio) <= 500', name='chk_users_bio_length'),
    sa.ForeignKeyConstraint(['access_jeton'], ['registration_jeton.id'], name='fk_users_access_jeton', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_access_jeton', 'users', ['access_jeton'], unique=False, postgresql_where=sa.text('access_jeton IS NOT NULL'))
    op.create_index('idx_users_can_post', 'users', ['can_post'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND can_post = true'))
    op.create_index('idx_users_classe', 'users', ['classe'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_created_at_id', 'users', ['created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_role', 'users', ['role'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_username', 'users', ['username'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_logs_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('club_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_in_club', sa.Enum('LEAD', 'CO_LEAD', 'EXECUTIVE_MEMBER', 'SIMPLE_MEMBER', name='clubmemberstype'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='fk_club_members_club', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_club_members_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_club_members_club_id', 'club_members', ['club_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_club_members_deleted_at', 'club_members', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_club_members_role_in_club', 'club_members', ['club_id', 'role_in_club'], unique=False, postgresql_where=sa.text("deleted_at IS NULL AND role_in_club IN ('LEAD', 'CO_LEAD')"))
    op.create_index('idx_club_members_user_id', 'club_members', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_club_members_club_user', 'club_members', ['club_id', 'user_id'], unique=True)
    op.create_table('moderation_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('moderator_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('DELETE_POST', 'DELETE_COMMENT', 'WARN_USER', 'SUSPEND_USER', 'RESTORE_POST', 'RESTORE_COMMENT', name='moderationactiontype'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('moderation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name='fk_moderation_logs_moderator', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_moderation_logs_created_at', 'moderation_logs', ['created_at'], unique=False)
    op.create_index('idx_moderation_logs_moderator', 'moderation_logs', ['moderator_id', 'created_at'], unique=False)
    op.create_index('idx_moderation_logs_target', 'moderation_logs', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(is_read = FALSE AND read_at IS NULL) OR (is_read = TRUE AND read_at IS NOT NULL)', name='chk_notifications_read_at'),
    sa.CheckConstraint('LENGTH(TRIM(message)) > 0', name='chk_notifications_message_not_empty'),
    sa.CheckConstraint('LENGTH(TRIM(title)) > 0', name='chk_notifications_title_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notifications_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_deleted_at', 'notifications', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_notifications_user_pagination', 'notifications', ['user_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_read = false'))
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('club_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'CAROUSSEL', name='posttype'), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("content IS NOT NULL OR post_type != 'TEXT'", name='chk_posts_content_required'),
    sa.CheckConstraint('content IS NULL OR LENGTH(content) <= 10000', name='chk_posts_content_length'),
    sa.CheckConstraint('like_count >= 0 AND comment_count >= 0', name='chk_posts_metrics'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_posts_author', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='fk_posts_club', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_posts_event', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_by_author', 'posts', ['author_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_posts_by_club', 'posts', ['club_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND club_id IS NOT NULL'))
    op.create_index('idx_posts_by_event', 'posts', ['event_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND event_id IS NOT NULL'))
    op.create_index('idx_posts_deleted_at', 'posts', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_posts_feed_pagination', 'posts', ['created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    op.create_index('idx_posts_pinned_feed', 'posts', ['is_pinned', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    op.create_index('idx_posts_popular', 'posts', ['like_count', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='chk_sessions_expires_after_creation'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_sessions_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_token_hash', 'sessions', ['token_hash'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id', 'last_activity_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('LENGTH(content) <= 2000', name='chk_comments_content_length'),
    sa.CheckConstraint('like_count >= 0 AND reply_count >= 0', name='chk_comments_metrics'),
    sa.CheckConstraint('parent_comment_id IS NULL OR parent_comment_id != id', name='chk_comments_no_self_parent'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_comments_author', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name='fk_comments_parent', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_comments_post', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_by_author', 'comments', ['author_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_comments_deleted_at', 'comments', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_comments_post_count', 'comments', ['post_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_comments_post_root', 'comments', ['post_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND parent_comment_id IS NULL'))
    op.create_index('idx_comments_replies', 'comments', ['parent_comment_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND parent_comment_id IS NOT NULL'))
    op.create_table('post_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(media_type = 'VIDEO' AND (duration IS NULL OR duration > 0)) OR (media_type = 'IMAGE' AND duration IS NULL)", name='chk_post_media_duration'),
    sa.CheckConstraint('(width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)', name='chk_post_media_dimensions'),
    sa.CheckConstraint('display_order >= 0', name='chk_post_media_display_order'),
    sa.CheckConstraint('file_size IS NULL OR file_size > 0', name='chk_post_media_file_size'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_post_media_post', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_media_deleted_at', 'post_media', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_post_media_is_processed', 'post_media', ['is_processed'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_processed = false'))
    op.create_index('idx_post_media_post_id', 'post_media', ['post_id', 'display_order'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('likes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('comment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL)', name='chk_likes_target'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='fk_likes_comment', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_likes_post', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_likes_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_likes_comment_id', 'likes', ['comment_id'], unique=False, postgresql_where=sa.text('comment_id IS NOT NULL'))
    op.create_index('idx_likes_comment_pagination', 'likes', ['comment_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('comment_id IS NOT NULL'))
    op.create_index('idx_likes_post_id', 'likes', ['post_id'], unique=False, postgresql_where=sa.text('post_id IS NOT NULL'))
    op.create_index('idx_likes_post_pagination', 'likes', ['post_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('post_id IS NOT NULL'))
    op.create_index('idx_likes_user_comment', 'likes', ['user_id', 'comment_id'], unique=False, postgresql_where=sa.text('comment_id IS NOT NULL'))
    op.create_index('idx_likes_user_post', 'likes', ['user_id', 'post_id'], unique=False, postgresql_where=sa.text('post_id IS NOT NULL'))
    op.create_index('uq_likes_user_comment', 'likes', ['user_id', 'comment_id'], unique=True)
    op.create_index('uq_likes_user_post', 'likes', ['user_id', 'post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_likes_user_post', table_name='likes')
    op.drop_index('uq_likes_user_comment', table_name='likes')
    op.drop_index('idx_likes_user_post', table_name='likes', postgresql_where=sa.text('post_id IS NOT NULL'))
    op.drop_index('idx_likes_user_comment', table_name='likes', postgresql_where=sa.text('comment_id IS NOT NULL'))
    op.drop_index('idx_likes_post_pagination', table_name='likes', postgresql_where=sa.text('post_id IS NOT NULL'))
    op.drop_index('idx_likes_post_id', table_name='likes', postgresql_where=sa.text('post_id IS NOT NULL'))
    op.drop_index('idx_likes_comment_pagination', table_name='likes', postgresql_where=sa.text('comment_id IS NOT NULL'))
    op.drop_index('idx_likes_comment_id', table_name='likes', postgresql_where=sa.text('comment_id IS NOT NULL'))
    op.drop_table('likes')
    op.drop_index('idx_post_media_post_id', table_name='post_media', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_post_media_is_processed', table_name='post_media', postgresql_where=sa.text('deleted_at IS NULL AND is_processed = false'))
    op.drop_index('idx_post_media_deleted_at', table_name='post_media', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('post_media')
    op.drop_index('idx_comments_replies', table_name='comments', postgresql_where=sa.text('deleted_at IS NULL AND parent_comment_id IS NOT NULL'))
    op.drop_index('idx_comments_post_root', table_name='comments', postgresql_where=sa.text('deleted_at IS NULL AND parent_comment_id IS NULL'))
    op.drop_index('idx_comments_post_count', table_name='comments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_comments_deleted_at', table_name='comments', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_comments_by_author', table_name='comments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('comments')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_token_hash', table_name='sessions')
    op.drop_index('idx_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_posts_popular', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    op.drop_index('idx_posts_pinned_feed', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    op.drop_index('idx_posts_feed_pagination', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    op.drop_index('idx_posts_deleted_at', table_name='posts', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_posts_by_event', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND event_id IS NOT NULL'))
    op.drop_index('idx_posts_by_club', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND club_id IS NOT NULL'))
    op.drop_index('idx_posts_by_author', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('posts')
    op.drop_index('idx_notifications_user_unread', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL AND is_read = false'))
    op.drop_index('idx_notifications_user_pagination', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_notifications_deleted_at', table_name='notifications', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('notifications')
    op.drop_index('idx_moderation_logs_target', table_name='moderation_logs')
    op.drop_index('idx_moderation_logs_moderator', table_name='moderation_logs')
    op.drop_index('idx_moderation_logs_created_at', table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index('uq_club_members_club_user', table_name='club_members')
    op.drop_index('idx_club_members_user_id', table_name='club_members', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_club_members_role_in_club', table_name='club_members', postgresql_where=sa.text("deleted_at IS NULL AND role_in_club IN ('LEAD', 'CO_LEAD')"))
    op.drop_index('idx_club_members_deleted_at', table_name='club_members', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_club_members_club_id', table_name='club_members', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('club_members')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_username', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_role', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_deleted_at', table_name='users', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_users_created_at_id', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_classe', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_can_post', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND can_post = true'))
    op.drop_index('idx_users_access_jeton', table_name='users', postgresql_where=sa.text('access_jeton IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('idx_events_status', table_name='events', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_events_start_date', table_name='events', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_events_slug', table_name='events', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_events_organizer_club_id', table_name='events', postgresql_where=sa.text('deleted_at IS NULL AND organizer_club_id IS NOT NULL'))
    op.drop_index('idx_events_deleted_at', table_name='events', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_events_created_at_id', table_name='events', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('events')
    op.drop_index('idx_registration_jeton_unused', table_name='registration_jeton', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_index('idx_registration_jeton_jeton', table_name='registration_jeton', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_index('idx_registration_jeton_classe', table_name='registration_jeton')
    op.drop_table('registration_jeton')
    op.drop_index('idx_clubs_slug', table_name='clubs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_clubs_is_active', table_name='clubs', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_index('idx_clubs_deleted_at', table_name='clubs', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_clubs_created_at_id', table_name='clubs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('clubs')
    # ### end Alembic commands ###
