"""Rectification des contraintes d'unicité sur User

Revision ID: 3e91d37c5a25
Revises: 8eb7e727c940
Create Date: 2026-04-04 06:49:16.444473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from alembic_postgresql_enum.sql_commands.indexes import TableIndex

# revision identifiers, used by Alembic.
revision: str = '3e91d37c5a25'
down_revision: Union[str, Sequence[str], None] = '8eb7e727c940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_users_email'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_users_username'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('uq_unique_conseiller_1'), table_name='users', postgresql_where="((executive_role = 'CONSEILLER_1'::executiveroletype) AND (deleted_at IS NULL))")
    op.drop_index(op.f('uq_unique_conseiller_2'), table_name='users', postgresql_where="((executive_role = 'CONSEILLER_2'::executiveroletype) AND (deleted_at IS NULL))")
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')

    op.sync_enum_values(
        enum_schema='public',
        enum_name='executiveroletype',
        new_values=['DELEGUE_GENERAL', 'DELEGUE_GENERAL_ADJOINT', 'SECRETAIRE_GENERAL', 'SECRETAIRE_GENERAL_ADJOINT', 'CACA', 'VICE_CACA', 'TRESORIER_GENERAL', 'VICE_TRESORIER_GENERAL', 'CONSEILLER'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='executive_role')],
        enum_values_to_rename=[],
        indexes_to_recreate=[
            TableIndex(
                name='public.uq_unique_caca',
                definition="CREATE UNIQUE INDEX uq_unique_caca ON public.users USING btree (executive_role) WHERE ((executive_role = 'CACA'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_delegue_general',
                definition="CREATE UNIQUE INDEX uq_unique_delegue_general ON public.users USING btree (executive_role) WHERE ((executive_role = 'DELEGUE_GENERAL'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_delegue_general_adjoint',
                definition="CREATE UNIQUE INDEX uq_unique_delegue_general_adjoint ON public.users USING btree (executive_role) WHERE ((executive_role = 'DELEGUE_GENERAL_ADJOINT'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_secretaire_general',
                definition="CREATE UNIQUE INDEX uq_unique_secretaire_general ON public.users USING btree (executive_role) WHERE ((executive_role = 'SECRETAIRE_GENERAL'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_secretaire_general_adjoint',
                definition="CREATE UNIQUE INDEX uq_unique_secretaire_general_adjoint ON public.users USING btree (executive_role) WHERE ((executive_role = 'SECRETAIRE_GENERAL_ADJOINT'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_tresorier_general',
                definition="CREATE UNIQUE INDEX uq_unique_tresorier_general ON public.users USING btree (executive_role) WHERE ((executive_role = 'TRESORIER_GENERAL'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_vice_caca',
                definition="CREATE UNIQUE INDEX uq_unique_vice_caca ON public.users USING btree (executive_role) WHERE ((executive_role = 'VICE_CACA'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_vice_tresorier_general',
                definition="CREATE UNIQUE INDEX uq_unique_vice_tresorier_general ON public.users USING btree (executive_role) WHERE ((executive_role = 'VICE_TRESORIER_GENERAL'::executiveroletype) AND (deleted_at IS NULL))",
            ),
        ],
    )
    op.create_index('uq_unique_conseiller', 'users', ['executive_role'], unique=True,
                    postgresql_where=sa.text("executive_role = 'CONSEILLER' AND deleted_at IS NULL"))
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_users_username', 'users', ['username'], unique=True,
                    postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='executiveroletype',
        new_values=['DELEGUE_GENERAL', 'DELEGUE_GENERAL_ADJOINT', 'SECRETAIRE_GENERAL', 'SECRETAIRE_GENERAL_ADJOINT', 'CACA', 'VICE_CACA', 'TRESORIER_GENERAL', 'VICE_TRESORIER_GENERAL', 'CONSEILLER_1', 'CONSEILLER_2'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='executive_role')],
        enum_values_to_rename=[],
        indexes_to_recreate=[
            TableIndex(
                name='public.uq_unique_caca',
                definition="CREATE UNIQUE INDEX uq_unique_caca ON public.users USING btree (executive_role) WHERE ((executive_role = 'CACA'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_conseiller_1',
                definition="CREATE UNIQUE INDEX uq_unique_conseiller_1 ON public.users USING btree (executive_role) WHERE ((executive_role = 'CONSEILLER_1'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_conseiller_2',
                definition="CREATE UNIQUE INDEX uq_unique_conseiller_2 ON public.users USING btree (executive_role) WHERE ((executive_role = 'CONSEILLER_2'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_delegue_general',
                definition="CREATE UNIQUE INDEX uq_unique_delegue_general ON public.users USING btree (executive_role) WHERE ((executive_role = 'DELEGUE_GENERAL'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_delegue_general_adjoint',
                definition="CREATE UNIQUE INDEX uq_unique_delegue_general_adjoint ON public.users USING btree (executive_role) WHERE ((executive_role = 'DELEGUE_GENERAL_ADJOINT'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_secretaire_general',
                definition="CREATE UNIQUE INDEX uq_unique_secretaire_general ON public.users USING btree (executive_role) WHERE ((executive_role = 'SECRETAIRE_GENERAL'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_secretaire_general_adjoint',
                definition="CREATE UNIQUE INDEX uq_unique_secretaire_general_adjoint ON public.users USING btree (executive_role) WHERE ((executive_role = 'SECRETAIRE_GENERAL_ADJOINT'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_tresorier_general',
                definition="CREATE UNIQUE INDEX uq_unique_tresorier_general ON public.users USING btree (executive_role) WHERE ((executive_role = 'TRESORIER_GENERAL'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_vice_caca',
                definition="CREATE UNIQUE INDEX uq_unique_vice_caca ON public.users USING btree (executive_role) WHERE ((executive_role = 'VICE_CACA'::executiveroletype) AND (deleted_at IS NULL))",
            ),
            TableIndex(
                name='public.uq_unique_vice_tresorier_general',
                definition="CREATE UNIQUE INDEX uq_unique_vice_tresorier_general ON public.users USING btree (executive_role) WHERE ((executive_role = 'VICE_TRESORIER_GENERAL'::executiveroletype) AND (deleted_at IS NULL))",
            ),
        ],
    )
    op.drop_index('uq_users_username', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_unique_conseiller', table_name='users', postgresql_where=sa.text("executive_role = 'CONSEILLER' AND deleted_at IS NULL"))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_unique_conseiller_2'), 'users', ['executive_role'], unique=True, postgresql_where="((executive_role = 'CONSEILLER_2'::executiveroletype) AND (deleted_at IS NULL))")
    op.create_index(op.f('uq_unique_conseiller_1'), 'users', ['executive_role'], unique=True, postgresql_where="((executive_role = 'CONSEILLER_1'::executiveroletype) AND (deleted_at IS NULL))")
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
