"""Ajouts de quelques index sur Story et Post

Revision ID: 4a288340bf1d
Revises: 10e1ef3fc24d
Create Date: 2026-04-07 14:29:15.424536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a288340bf1d'
down_revision: Union[str, Sequence[str], None] = '10e1ef3fc24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_post_views_feed_pagination', 'post_views', ['post_id', 'user_id'], unique=False)
    op.create_index('idx_club_post', 'posts', ['club_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND club_id IS NOT NULL'))
    op.create_index('idx_event_post', 'posts', ['event_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND event_id IS NOT NULL'))
    op.create_index('idx_user_post', 'posts', ['author_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_story_view_feed_pagination', 'story_views', ['story_id', 'viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_story_view_feed_pagination', table_name='story_views')
    op.drop_index('idx_user_post', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_event_post', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND event_id IS NOT NULL'))
    op.drop_index('idx_club_post', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND club_id IS NOT NULL'))
    op.drop_index('idx_post_views_feed_pagination', table_name='post_views')
    # ### end Alembic commands ###
