"""Ajouts de la tables story group

Revision ID: 534fd4d712d7
Revises: 4a288340bf1d
Create Date: 2026-04-08 07:17:07.318460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534fd4d712d7'
down_revision: Union[str, Sequence[str], None] = '4a288340bf1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_story_groups_author', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_story_groups_author', 'story_groups', ['author_id'], unique=False, postgresql_where=sa.text('is_expired = false'))
    op.create_index('idx_story_groups_expiration', 'story_groups', ['expires_at'], unique=False, postgresql_where=sa.text('is_expired = false'))
    op.create_index('idx_story_groups_feed', 'story_groups', [sa.literal_column('updated_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text('is_expired = false'))
    op.create_index('uq_author_active_group', 'story_groups', ['author_id'], unique=True, postgresql_where=sa.text('is_expired = false'))
    op.add_column('stories', sa.Column('group_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('fk_stories_group', 'stories', 'story_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stories_group', 'stories', type_='foreignkey')
    op.drop_column('stories', 'group_id')
    op.drop_index('uq_author_active_group', table_name='story_groups', postgresql_where=sa.text('is_expired = false'))
    op.drop_index('idx_story_groups_feed', table_name='story_groups', postgresql_where=sa.text('is_expired = false'))
    op.drop_index('idx_story_groups_expiration', table_name='story_groups', postgresql_where=sa.text('is_expired = false'))
    op.drop_index('idx_story_groups_author', table_name='story_groups', postgresql_where=sa.text('is_expired = false'))
    op.drop_table('story_groups')
    # ### end Alembic commands ###
