"""Modification de la structure de event, ajout du nom de contrainte

Revision ID: 5d60e31b2643
Revises: c6b8d313cebb
Create Date: 2026-03-24 15:07:30.421466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d60e31b2643'
down_revision: Union[str, Sequence[str], None] = 'c6b8d313cebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_slug_key'), 'events', type_='unique')
    op.create_index('uq_events_slug', 'events', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_events_slug', table_name='events', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_unique_constraint(op.f('events_slug_key'), 'events', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
