"""Supression attribut token_hash dans la table Session

Revision ID: 74dab7082f59
Revises: 02a065f93b39
Create Date: 2026-02-19 00:15:20.876392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74dab7082f59'
down_revision: Union[str, Sequence[str], None] = '02a065f93b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'refresh_token_hash',
               existing_type=sa.VARCHAR(length=255), 
               unique=True,
               nullable=False)
    op.drop_index(op.f('idx_sessions_token_hash'), table_name='sessions')
    op.drop_constraint(op.f('sessions_token_hash_key'), 'sessions', type_='unique')
    op.create_index('idx_sessions_ref_token_hash', 'sessions', ['refresh_token_hash'], unique=False)
    op.create_unique_constraint(None, 'sessions', ['refresh_token_hash'])
    op.drop_column('sessions', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_index('idx_sessions_ref_token_hash', table_name='sessions')
    op.create_unique_constraint(op.f('sessions_token_hash_key'), 'sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sessions_token_hash'), 'sessions', ['token_hash'], unique=False)
    op.alter_column('sessions', 'refresh_token_hash',
               existing_type=sa.VARCHAR(length=255), 
               unique=False,
               nullable=True)
    # ### end Alembic commands ###
