"""MAJ de la contrainte d'unicité sur libelle dans academic_year

Revision ID: 778de99102f7
Revises: 097b0856e30f
Create Date: 2026-03-14 18:18:44.990106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778de99102f7'
down_revision: Union[str, Sequence[str], None] = '097b0856e30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('academic_year_libelle_key'), 'academic_year', type_='unique')
    op.create_index('uq_academic_year_libelle', 'academic_year', ['libelle'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_academic_year_libelle', table_name='academic_year', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('academic_year_libelle_key'), 'academic_year', ['libelle'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
