"""Ajout de champs par de message lisible dans la table Audit et Log

Revision ID: 784791b2a7f4
Revises: 74dab7082f59
Create Date: 2026-02-19 22:57:52.225185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784791b2a7f4'
down_revision: Union[str, Sequence[str], None] = '74dab7082f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('readable_message', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'readable_message')
    # ### end Alembic commands ###
