"""Retrait des attributs inutile dans la table User

Revision ID: 7ef5c8c64122
Revises: 08395946c10d
Create Date: 2026-02-22 11:49:10.648025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ef5c8c64122'
down_revision: Union[str, Sequence[str], None] = '08395946c10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_jeton_id', sa.Uuid(), nullable=True, comment="Référence au jeton d'inscription utilisé"))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_users_access_jeton'), table_name='users', postgresql_where='(access_jeton IS NOT NULL)')
    op.create_index('idx_users_access_jeton', 'users', ['access_jeton_id'], unique=False, postgresql_where=sa.text('access_jeton_id IS NOT NULL'))
    op.drop_constraint(op.f('fk_users_access_jeton'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_access_jeton', 'users', 'registration_jeton', ['access_jeton_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'access_jeton')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'mfa_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('mfa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('access_jeton', sa.UUID(), autoincrement=False, nullable=True, comment="Référence au jeton d'inscription utilisé"))
    op.drop_constraint('fk_users_access_jeton', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_access_jeton'), 'users', 'registration_jeton', ['access_jeton'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_users_access_jeton', table_name='users', postgresql_where=sa.text('access_jeton_id IS NOT NULL'))
    op.create_index(op.f('idx_users_access_jeton'), 'users', ['access_jeton'], unique=False, postgresql_where='(access_jeton IS NOT NULL)')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('users', 'access_jeton_id')
    # ### end Alembic commands ###
