"""Ajouts d'indexs pour les story

Revision ID: 806f65f55044
Revises: 1afa64907ee9
Create Date: 2026-04-10 13:45:00.626546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806f65f55044'
down_revision: Union[str, Sequence[str], None] = '1afa64907ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_story_groups_author', 'story_groups', ['author_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_story_groups_classe_pagination', 'story_groups', ['target_classe_id', sa.literal_column('expires_at DESC'), sa.literal_column('updated_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text("is_active = true AND group_type = 'CLASSE_GROUP'"))
    op.create_index('idx_story_groups_expiration', 'story_groups', ['expires_at'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_story_groups_feed', 'story_groups', [sa.literal_column('updated_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_story_groups_feed_optimized', 'story_groups', ['group_type', sa.literal_column('expires_at DESC'), sa.literal_column('updated_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('uq_author_active_group', 'story_groups', ['author_id'], unique=True, postgresql_where=sa.text("is_active = true AND author_id IS NOT NULL AND group_type = 'USER_GROUP'"))
    op.create_index('idx_story_views_by_user_story', 'story_views', ['user_id', 'story_id'], unique=False)
    op.create_index('idx_story_views_user_lookup', 'story_views', ['story_id', 'user_id', 'viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_story_views_user_lookup', table_name='story_views')
    op.drop_index('idx_story_views_by_user_story', table_name='story_views')
    op.drop_index('uq_author_active_group', table_name='story_groups', postgresql_where=sa.text("is_active = true AND author_id IS NOT NULL AND group_type = 'USER_GROUP'"))
    op.drop_index('idx_story_groups_feed_optimized', table_name='story_groups', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_story_groups_feed', table_name='story_groups', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_story_groups_expiration', table_name='story_groups', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_story_groups_classe_pagination', table_name='story_groups', postgresql_where=sa.text("is_active = true AND group_type = 'CLASSE_GROUP'"))
    op.drop_index('idx_story_groups_author', table_name='story_groups', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###
