"""Ajout de l'enum pour gerer le cas de executive_member

Revision ID: 89799dbf9a87
Revises: 2c00283384af
Create Date: 2026-02-10 16:04:43.615601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '89799dbf9a87'
down_revision: Union[str, Sequence[str], None] = '2c00283384af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DELEGUE_GENERAL', 'DELEGUE_GENERAL_ADJOINT', 'SECRETAIRE_GENERAL', 'SECRETAIRE_GENERAL_ADJOINT', 'CACA', 'VICE_CACA', 'TRESORIER_GENERAL', 'VICE_TRESORIER_GENERAL', 'CONSEILLER_1', 'CONSEILLER_2', name='executiveroletype').create(op.get_bind())
    op.sync_enum_values(
        enum_schema='public',
        enum_name='userrole',
        new_values=['STUDENT', 'CLUB_LEADER', 'DELEGATE', 'MODERATOR', 'ADMIN', 'SPECTATOR', 'EXECUTIVE_MEMBER'],
        affected_columns=[TableReference(table_schema='public', table_name='registration_jeton', column_name='role'), TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    op.add_column('users', sa.Column('executive_role', sa.Enum('DELEGUE_GENERAL', 'DELEGUE_GENERAL_ADJOINT', 'SECRETAIRE_GENERAL', 'SECRETAIRE_GENERAL_ADJOINT', 'CACA', 'VICE_CACA', 'TRESORIER_GENERAL', 'VICE_TRESORIER_GENERAL', 'CONSEILLER_1', 'CONSEILLER_2', name='executiveroletype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'executive_role')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='userrole',
        new_values=['STUDENT', 'CLUB_LEADER', 'DELEGATE', 'GENERAL_DELEGATE', 'SECRETAIRE_GENERAL', 'EXECUTIVE_MEMBER', 'MODERATOR', 'ADMIN', 'SPECTATOR'],
        affected_columns=[TableReference(table_schema='public', table_name='registration_jeton', column_name='role'), TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    sa.Enum('DELEGUE_GENERAL', 'DELEGUE_GENERAL_ADJOINT', 'SECRETAIRE_GENERAL', 'SECRETAIRE_GENERAL_ADJOINT', 'CACA', 'VICE_CACA', 'TRESORIER_GENERAL', 'VICE_TRESORIER_GENERAL', 'CONSEILLER_1', 'CONSEILLER_2', name='executiveroletype').drop(op.get_bind())
    # ### end Alembic commands ###
