"""Rectification de la contrainte d'unicité dans club_members

Revision ID: 8eb7e727c940
Revises: fb78b5a40df7
Create Date: 2026-04-01 15:03:17.404185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb7e727c940'
down_revision: Union[str, Sequence[str], None] = 'fb78b5a40df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_club_members_club_user', table_name='club_members')
    op.create_index(op.f('uq_club_members_club_user'), 'club_members', ['club_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_club_members_club_user'), table_name='club_members')
    op.create_index(op.f('uq_club_members_club_user'), 'club_members', ['club_id', 'user_id'], unique=True)
    # ### end Alembic commands ###
