"""Ajout des contraintes d'unicité sur tous les roles de la table users

Revision ID: 9db90c0cbe55
Revises: 5d60e31b2643
Create Date: 2026-03-28 01:44:02.093274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db90c0cbe55'
down_revision: Union[str, Sequence[str], None] = '5d60e31b2643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_unique_caca', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'CACA' AND deleted_at IS NULL"))
    op.create_index('uq_unique_conseiller_1', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'CONSEILLER_1' AND deleted_at IS NULL"))
    op.create_index('uq_unique_conseiller_2', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'CONSEILLER_2' AND deleted_at IS NULL"))
    op.create_index('uq_unique_delegue_general', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'DELEGUE_GENERAL' AND deleted_at IS NULL"))
    op.create_index('uq_unique_delegue_general_adjoint', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'DELEGUE_GENERAL_ADJOINT' AND deleted_at IS NULL"))
    op.create_index('uq_unique_secretaire_general', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'SECRETAIRE_GENERAL' AND deleted_at IS NULL"))
    op.create_index('uq_unique_secretaire_general_adjoint', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'SECRETAIRE_GENERAL_ADJOINT' AND deleted_at IS NULL"))
    op.create_index('uq_unique_tresorier_general', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'TRESORIER_GENERAL' AND deleted_at IS NULL"))
    op.create_index('uq_unique_vice_caca', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'VICE_CACA' AND deleted_at IS NULL"))
    op.create_index('uq_unique_vice_tresorier_general', 'users', ['executive_role'], unique=True, postgresql_where=sa.text("executive_role = 'VICE_TRESORIER_GENERAL' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_unique_vice_tresorier_general', table_name='users', postgresql_where=sa.text("executive_role = 'VICE_TRESORIER_GENERAL' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_vice_caca', table_name='users', postgresql_where=sa.text("executive_role = 'VICE_CACA' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_tresorier_general', table_name='users', postgresql_where=sa.text("executive_role = 'TRESORIER_GENERAL' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_secretaire_general_adjoint', table_name='users', postgresql_where=sa.text("executive_role = 'SECRETAIRE_GENERAL_ADJOINT' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_secretaire_general', table_name='users', postgresql_where=sa.text("executive_role = 'SECRETAIRE_GENERAL' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_delegue_general_adjoint', table_name='users', postgresql_where=sa.text("executive_role = 'DELEGUE_GENERAL_ADJOINT' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_delegue_general', table_name='users', postgresql_where=sa.text("executive_role = 'DELEGUE_GENERAL' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_conseiller_2', table_name='users', postgresql_where=sa.text("executive_role = 'CONSEILLER_2' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_conseiller_1', table_name='users', postgresql_where=sa.text("executive_role = 'CONSEILLER_1' AND deleted_at IS NULL"))
    op.drop_index('uq_unique_caca', table_name='users', postgresql_where=sa.text("executive_role = 'CACA' AND deleted_at IS NULL"))
    # ### end Alembic commands ###
