"""ajoute des contraintes de creations sur la tables event

Revision ID: c6b8d313cebb
Revises: 778de99102f7
Create Date: 2026-03-22 21:03:24.895812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b8d313cebb'
down_revision: Union[str, Sequence[str], None] = '778de99102f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_events_date_title', 'events', ['title', 'start_date'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_events_date_title', table_name='events', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
