"""Ajouts de nouvelles colonnes sur story

Revision ID: c8979b798939
Revises: 806f65f55044
Create Date: 2026-04-10 14:06:00.826844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8979b798939'
down_revision: Union[str, Sequence[str], None] = '806f65f55044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('stories', sa.Column('blur_hash', sa.String(length=255), nullable=True))
    op.add_column('stories', sa.Column('stored_bucket_name', sa.String(length=255), nullable=True))

    # Mettre à jour toutes les lignes existantes avec la valeur par défaut
    op.execute(
        sa.text("UPDATE stories SET stored_bucket_name = 'stories-ephemeral-content' WHERE stored_bucket_name IS NULL")
    )

    op.alter_column('stories', 'stored_bucket_name', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'stored_bucket_name')
    op.drop_column('stories', 'blur_hash')
    # ### end Alembic commands ###
