"""Ajout de nouveaux index sur la table posts

Revision ID: d2a91ddcd8ad
Revises: 2834fc41e8b7
Create Date: 2026-04-01 10:57:55.771487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a91ddcd8ad'
down_revision: Union[str, Sequence[str], None] = '2834fc41e8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_posts_academic_year', 'posts', ['academic_year_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_academic_year', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
