"""Ajout colonne executive_role dans RegistrationJeton

Revision ID: e10e8b71cfb5
Revises: 8eb7e727c940
Create Date: 2026-04-03 21:46:38.694349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e10e8b71cfb5'
down_revision: Union[str, Sequence[str], None] = '8eb7e727c940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_jeton', sa.Column('executive_role', postgresql.ENUM('DELEGUE_GENERAL', 'DELEGUE_GENERAL_ADJOINT', 'SECRETAIRE_GENERAL', 'SECRETAIRE_GENERAL_ADJOINT', 'CACA', 'VICE_CACA', 'TRESORIER_GENERAL', 'VICE_TRESORIER_GENERAL', 'CONSEILLER_1', 'CONSEILLER_2', name='executiveroletype', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_jeton', 'executive_role')
    # ### end Alembic commands ###
