"""Ajout colonne email dans RegistrationJeton

Revision ID: e6be234bf22a
Revises: 534fd4d712d7
Create Date: 2026-04-08 13:45:15.875487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6be234bf22a'
down_revision: Union[str, Sequence[str], None] = '534fd4d712d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_jeton', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index('uq_registration_jeton_email', 'registration_jeton', ['email'], unique=True, postgresql_where=sa.text('used_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_registration_jeton_email', table_name='registration_jeton', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_column('registration_jeton', 'email')
    # ### end Alembic commands ###
