"""Ajout encore de nouveaux index sur la table posts

Revision ID: fb78b5a40df7
Revises: d2a91ddcd8ad
Create Date: 2026-04-01 12:29:57.054833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb78b5a40df7'
down_revision: Union[str, Sequence[str], None] = 'd2a91ddcd8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_posts_feed_by_year', 'posts', ['academic_year_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    op.create_index('idx_posts_feed_by_year_classe', 'posts', ['academic_year_id', 'target_classe_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_feed_by_year_classe', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    op.drop_index('idx_posts_feed_by_year', table_name='posts', postgresql_where=sa.text('deleted_at IS NULL AND is_published = true'))
    # ### end Alembic commands ###
