# Définition de la zone de cache (1 Go max, les clés stockées 60 min en RAM)
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC_CACHE:10m inactive=24h max_size=1g;

server {
    listen 80;
    server_name api.iai-journal.test;

    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Pas de cache pour l'API
        proxy_cache off;
    }
}

server {
    listen 80;
    server_name media.iai-journal.test;

    location / {
        proxy_pass http://minio:9001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # --- OPTIMISATION CACHE ---
        proxy_cache STATIC_CACHE;
        proxy_cache_valid 200 302 24h;  # Cache les images/vidéos réussies pendant 24h
        proxy_cache_valid 404 1m;       # Cache les erreurs 404 seulement 1 min
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        add_header X-Cache-Status $upstream_cache_status;   # Pour vérifier si le cache fonctionne

        # --- SUPPORT HLS & STREAMING ---
        # Permet au navigateur de demander des morceaux de vidéo (Range Requests)
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_no_cache $http_range;     # Désactive le cache uniquement si la requête est spécifique (optionnel)

        # Types de fichiers pour le HLS
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }
    }
}

server {
    listen 80;
    server_name flower.iai-journal.test;

    location / {
        proxy_pass http://flower:5555;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Pas de cache
        proxy_cache off;
    }
}


# On pourra ajouter d'autres locations pour d'autres services si besoin (ex: front, dashboard admin, etc.)
